*** empty log message ***

diff --git a/install/test_all b/install/test_all
--- a/install/test_all
+++ b/install/test_all
@@ -10,6 +10,7 @@ unsetenv ADDBUILDNO
 endif
 
 setenv ARCH linuxicc
+echo "Testing $ARCH"
 $AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
 set i=$?
 if ( "$i" < 0 ) then
@@ -18,6 +19,17 @@ endif
 
 
 setenv ARCH PGlinuxicc
+echo "Testing $ARCH"
+$AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
+set i=$?
+if ( "$i" < 0 ) then
+echo "$ARCH failed $i"
+endif
+
+
+setenv ARCH PGLinux.24
+echo "Testing $ARCH"
+
 $AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
 set i=$?
 if ( "$i" < 0 ) then
@@ -28,6 +40,15 @@ endif
 
 
 setenv ARCH linux
+echo "Testing $ARCH"
+$AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
+set i=$?
+if ( "$i" < 0 ) then
+echo "$ARCH failed $i"
+endif
+
+setenv ARCH Linux.24
+echo "Testing $ARCH"
 $AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
 set i=$?
 if ( "$i" < 0 ) then
@@ -37,6 +58,7 @@ endif
 
 
 setenv ARCH PGlinux
+echo "Testing $ARCH"
 $AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
 set i=$?
 if ( "$i" < 0 ) then
@@ -45,6 +67,7 @@ endif
 
 
 setenv ARCH linuxx8664icc
+echo "Testing $ARCH"
 $AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
 set i=$?
 if ( "$i" < 0 ) then
@@ -54,6 +77,7 @@ endif
 
 
 setenv ARCH PGlinuxx8664icc
+echo "Testing $ARCH"
 $AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
 set i=$?
 if ( "$i" < 0 ) then
